Update nodecover.js
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.

I've removed the require.paths from the nodecover.js file so it runs with the latest node.